title: m1ffyz
author: m1ffyz
twitter_username: m1ffyz
github_username: m1ffyz

header_pages:
  - index.md
  - profile.md

date_format: "%Y年 %m月 %d日"

theme: minima

minima:
  date_format: "%Y年 %m月 %d日"

timezone: Asia/Tokyo

paginate: 10